std = {
	globals =
	{
		-- WoW Vars
		"C_ChallengeMode",
		"C_Club",
		"C_GuildInfo",
		"C_Map",
		"C_MythicPlus",
		"ChatFrame_SendTell",
		"CheckInteractDistance",
		"CommunitiesFrame",
		"CreateColor",
		"CreateFrame",
		"CreateMacro",
		"GameFontNormal",
		"GetClassColor",
		"GetClassInfo",
		"GetCursorPosition",
		"GetGuildInfo",
		"GetGuildRosterInfo",
		"GetNumGuildMembers",
		"GetServerTime",
		"HIGHLIGHT_FONT_COLOR_CODE",
		"HybridScrollFrame_CreateButtons",
		"HybridScrollFrame_GetOffset",
		"HybridScrollFrame_SetDoNotHideScrollBar",
		"HybridScrollFrame_Update",
		"InterfaceOptionsFrame_OpenToCategory",
		"INVITE",
		"InviteUnit",
		"IsInGuild",
		"IsInRaid",
		"LibStub",
		"MacroFrame",
		"PanelTemplates_TabResize",
		"PlaySound",
		"PlaySoundFile",
		"SCROLLING_MESSAGE_FRAME_INSERT_MODE_TOP",
		"SendChatMessage",
		"ShowUIPanel",
		"SOUNDKIT",
		"ToggleDropDownMenu",
		"UIDropDownMenu_AddButton",
		"UIDropDownMenu_CreateInfo",
		"UIDropDownMenu_Initialize",
		"UIParent",
		"UISpecialFrames",
		"UnitClass",
		"UnitFactionGroup",
		"UnitFullName",
		"UnitGUID",
		"UnitName",
		"UnitRace",
		"UnitSex",
		"WHISPER",

		"WCCC_MythicPlusEntryMixin",
		"WCCC_MythicPlus_Frame",
		"WCCC_MythicPlusFrameMixin",
		"WCCC_MythicPlus_OnColumnClick",

		-- lua std funcs, not sure why these are flagged?
		"ceil",
		"date",
		"format",
		"ipairs",
		"math",
		"next",
		"pairs",
		"print",
		"random",		
		"setmetatable",
		"string",
		"table",
		"time",
		"tinsert",
		"tonumber",
		"tostring",
		"type",
	}
}

ignore = {"212/self", "612", "614", "631"}